// apps/Money Transfer Table/components/add-recipient-modal.tsx
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { recipients } from "@/data/recipients"
import { transferReasons } from "@/data/transfer-reasons"
import type { TransferRow } from "@/components/money-transfer-table"

interface AddRecipientModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onAdd: (recipient: Omit<TransferRow, "id" | "currency" | "amount">) => void
  receivingCurrency: string
}

export function AddRecipientModal({ open, onOpenChange, onAdd, receivingCurrency }: AddRecipientModalProps) {
  const [selectedRecipientId, setSelectedRecipientId] = useState("")
  const [reason, setReason] = useState("Payment")
  const [reference, setReference] = useState("")

  const handleSubmit = () => {
    const selectedRecipient = recipients.find((r) => r.id === selectedRecipientId)
    if (!selectedRecipient) return

    onAdd({
      recipient: selectedRecipient,
      reason,
      reference,
    })

    // Reset form
    setSelectedRecipientId("")
    setReason("Payment")
    setReference("")
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Add Recipient</DialogTitle>
          <DialogDescription>Add a new recipient to your money transfer.</DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="recipient">
              Recipient <span className="text-sm text-muted-foreground">({receivingCurrency} recipients)</span>
            </Label>
            <Select value={selectedRecipientId} onValueChange={setSelectedRecipientId}>
              <SelectTrigger id="recipient">
                <SelectValue placeholder="Select recipient" />
              </SelectTrigger>
              <SelectContent>
                {recipients.map((recipient) => (
                  <SelectItem key={recipient.id} value={recipient.id}>
                    {recipient.name} ({recipient.email})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-xs text-muted-foreground">Only showing recipients who can receive {receivingCurrency}</p>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="reason">Reason</Label>
            <Select value={reason} onValueChange={setReason}>
              <SelectTrigger id="reason">
                <SelectValue placeholder="Select reason" />
              </SelectTrigger>
              <SelectContent>
                {transferReasons.map((reason) => (
                  <SelectItem key={reason} value={reason}>
                    {reason}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="reference">Reference (Optional)</Label>
            <Input
              id="reference"
              value={reference}
              onChange={(e) => setReference(e.target.value)}
              placeholder="Add a reference"
            />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleSubmit} disabled={!selectedRecipientId}>
            Add Recipient
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// apps/frontend/unused/multipay/components/AddRecipientModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import Input from '@/components/ui/input/Input.vue'
import Button from '@/components/ui/button/Button.vue'
import Dialog from '@/components/ui/dialog/Dialog.vue'
import DialogContent from '@/components/ui/dialog/DialogContent.vue'
import DialogHeader from '@/components/ui/dialog/DialogHeader.vue'
import DialogTitle from '@/components/ui/dialog/DialogTitle.vue'
import DialogDescription from '@/components/ui/dialog/DialogDescription.vue'
import DialogFooter from '@/components/ui/dialog/DialogFooter.vue'
import Label from '@/components/ui/label/Label.vue'
import Select from '@/components/ui/select/Select.vue'
import SelectTrigger from '@/components/ui/select/SelectTrigger.vue'
import SelectValue from '@/components/ui/select/SelectValue.vue'
import SelectContent from '@/components/ui/select/SelectContent.vue'
import SelectItem from '@/components/ui/select/SelectItem.vue'

const props = defineProps<{
  open: boolean
  onOpenChange: (open: boolean) => void
  onAdd: (recipient: { recipient: any; reason: string; reference: string }) => void
  receivingCurrency: string
  recipients: any[]
  transferReasons: string[]
}>()

const selectedRecipientId = ref('')
const reason = ref(String(props.transferReasons[0] || ''))
const reference = ref('')

watch(
  () => props.open,
  (open) => {
    if (!open) {
      selectedRecipientId.value = ''
      reason.value = String(props.transferReasons[0] || '')
      reference.value = ''
    }
  },
)

const handleSubmit = () => {
  const selectedRecipient = props.recipients.find((r: any) => r.id === selectedRecipientId.value)
  if (!selectedRecipient) return
  props.onAdd({
    recipient: selectedRecipient,
    reason: String(reason.value),
    reference: reference.value,
  })
  // Reset form
  selectedRecipientId.value = ''
  reason.value = String(props.transferReasons[0] || '')
  reference.value = ''
  props.onOpenChange(false)
}
</script>

<template>
  <Dialog :open="open" @update:open="onOpenChange">
    <DialogContent class="sm:max-w-[425px]">
      <DialogHeader>
        <DialogTitle>Add Recipient</DialogTitle>
        <DialogDescription>Add a new recipient to your money transfer.</DialogDescription>
      </DialogHeader>
      <div class="gap-4 grid py-4">
        <div class="gap-2 grid">
          <Label for="recipient">
            Recipient
            <span class="text-muted-foreground text-sm">({{ receivingCurrency }} recipients)</span>
          </Label>
          <Select v-model="selectedRecipientId">
            <SelectTrigger id="recipient">
              <SelectValue placeholder="Select recipient" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="recipient in recipients" :key="recipient.id" :value="recipient.id">
                {{ recipient.name }} ({{ recipient.email }})
              </SelectItem>
            </SelectContent>
          </Select>
          <p class="text-muted-foreground text-xs">
            Only showing recipients who can receive {{ receivingCurrency }}
          </p>
        </div>
        <div class="gap-2 grid">
          <Label for="reason">Reason</Label>
          <Select v-model="reason">
            <SelectTrigger id="reason">
              <SelectValue placeholder="Select reason" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="reason in transferReasons" :key="reason" :value="reason">
                {{ reason }}
              </SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div class="gap-2 grid">
          <Label for="reference">Reference (Optional)</Label>
          <Input id="reference" v-model="reference" placeholder="Add a reference" />
        </div>
      </div>
      <DialogFooter>
        <Button variant="outline" @click="onOpenChange(false)"> Cancel </Button>
        <Button @click="handleSubmit" :disabled="!selectedRecipientId"> Add Recipient </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
